title: Journey of a new Python learner
author: sgcsf.slr
email: sgcsf.slr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This new site will be a depository of the python scripts that was created during my learning from videos and files, 
  they will searve as a reference to me or anyone who are interested to about python. 
  If you spot any python scripts that I have created that could have been better or more efficiently scripted, 
  please feel free to share so that I can learn and improve. 
  It is never too old for me to learn. Keep learning. 
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
